/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding-complete'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SuperadminRouteRouteImport } from './routes/superadmin/route'
import { Route as HostelRouteRouteImport } from './routes/hostel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin/login'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin/dashboard'
import { Route as HostelDashboardRouteImport } from './routes/hostel/dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as HostelVerifyStudentIdRouteImport } from './routes/hostel/verify.$studentId'

const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding-complete',
  path: '/onboarding-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRouteRoute = SuperadminRouteRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRouteRoute = HostelRouteRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const HostelDashboardRoute = HostelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HostelRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/admin/__layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelVerifyStudentIdRoute = HostelVerifyStudentIdRouteImport.update({
  id: '/verify/$studentId',
  path: '/verify/$studentId',
  getParentRoute: () => HostelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hostel': typeof HostelRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-complete': typeof OnboardingCompleteRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/users': typeof AdminUsersRoute
  '/hostel/dashboard': typeof HostelDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/hostel/verify/$studentId': typeof HostelVerifyStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hostel': typeof HostelRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-complete': typeof OnboardingCompleteRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/users': typeof AdminUsersRoute
  '/hostel/dashboard': typeof HostelDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/hostel/verify/$studentId': typeof HostelVerifyStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hostel': typeof HostelRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-complete': typeof OnboardingCompleteRoute
  '/admin/__layout': typeof Admin_layoutRoute
  '/admin/users': typeof AdminUsersRoute
  '/hostel/dashboard': typeof HostelDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/hostel/verify/$studentId': typeof HostelVerifyStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hostel'
    | '/superadmin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/onboarding-complete'
    | '/admin'
    | '/admin/users'
    | '/hostel/dashboard'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/hostel/verify/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hostel'
    | '/superadmin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/onboarding-complete'
    | '/admin'
    | '/admin/users'
    | '/hostel/dashboard'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/hostel/verify/$studentId'
  id:
    | '__root__'
    | '/'
    | '/hostel'
    | '/superadmin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/onboarding-complete'
    | '/admin/__layout'
    | '/admin/users'
    | '/hostel/dashboard'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/hostel/verify/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostelRouteRoute: typeof HostelRouteRouteWithChildren
  SuperadminRouteRoute: typeof SuperadminRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding-complete': {
      id: '/onboarding-complete'
      path: '/onboarding-complete'
      fullPath: '/onboarding-complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/hostel/dashboard': {
      id: '/hostel/dashboard'
      path: '/dashboard'
      fullPath: '/hostel/dashboard'
      preLoaderRoute: typeof HostelDashboardRouteImport
      parentRoute: typeof HostelRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel/verify/$studentId': {
      id: '/hostel/verify/$studentId'
      path: '/verify/$studentId'
      fullPath: '/hostel/verify/$studentId'
      preLoaderRoute: typeof HostelVerifyStudentIdRouteImport
      parentRoute: typeof HostelRouteRoute
    }
  }
}

interface HostelRouteRouteChildren {
  HostelDashboardRoute: typeof HostelDashboardRoute
  HostelVerifyStudentIdRoute: typeof HostelVerifyStudentIdRoute
}

const HostelRouteRouteChildren: HostelRouteRouteChildren = {
  HostelDashboardRoute: HostelDashboardRoute,
  HostelVerifyStudentIdRoute: HostelVerifyStudentIdRoute,
}

const HostelRouteRouteWithChildren = HostelRouteRoute._addFileChildren(
  HostelRouteRouteChildren,
)

interface SuperadminRouteRouteChildren {
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

const SuperadminRouteRouteChildren: SuperadminRouteRouteChildren = {
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
}

const SuperadminRouteRouteWithChildren = SuperadminRouteRoute._addFileChildren(
  SuperadminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostelRouteRoute: HostelRouteRouteWithChildren,
  SuperadminRouteRoute: SuperadminRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  Admin_layoutRoute: Admin_layoutRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
